import type { Category } from "@/types";

export const DEFAULT_CATEGORIES: Omit<Category, "id" | "createdAt">[] = [
  {
    name: "Food & Dining",
    keywords: [
      "swiggy",
      "zomato",
      "eatclub",
      "farsan",
      "swad",
      "restaurant",
      "food",
      "cafe",
      "kitchen",
      "biryani",
      "pizza",
      "burger",
      "hotel",
      "dhaba",
      "mcdonald",
      "kfc",
      "dominos",
      "subway",
      "chai",
      "barbeque",
    ],
    color: "orange",
    icon: "ForkKnife",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Groceries",
    keywords: [
      "amazonpaygrocery",
      "zepto",
      "blinkit",
      "bigbasket",
      "grofers",
      "dmart",
      "reliance fresh",
      "more retail",
      "vegetables",
      "kirana",
      "instamart",
      "dunzo",
      "jiomart",
      "milk",
      "bread",
    ],
    color: "green",
    icon: "ShoppingCart",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Water",
    keywords: ["drinkprime", "water", "aqua", "bisleri"],
    color: "blue",
    icon: "Drop",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Healthcare",
    keywords: [
      "medplus",
      "hospital",
      "pharmacy",
      "pharma",
      "medical",
      "apollo",
      "netmeds",
      "1mg",
      "health",
      "doctor",
      "clinic",
      "wellness",
      "practo",
      "fortis",
      "max healthcare",
      "manipal",
    ],
    color: "red",
    icon: "FirstAidKit",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Shopping",
    keywords: [
      "amazon",
      "flipkart",
      "myntra",
      "ajio",
      "meesho",
      "snapdeal",
      "nykaa",
      "lenskart",
      "pepperfry",
      "urban ladder",
      "tata cliq",
    ],
    color: "purple",
    icon: "Bag",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Services",
    keywords: [
      "urban company",
      "urbancompany",
      "mixed wash",
      "mixedwash",
      "laundry",
      "salon",
      "parlour",
      "spa",
      "massage",
      "cleaning",
    ],
    color: "pink",
    icon: "Scissors",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Cloud & Tech",
    keywords: [
      "google cloud",
      "aws",
      "azure",
      "digital ocean",
      "vercel",
      "netlify",
      "heroku",
      "github",
      "domain",
      "hosting",
      "render",
    ],
    color: "cyan",
    icon: "Cloud",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Transport",
    keywords: [
      "uber",
      "ola",
      "rapido",
      "metro",
      "irctc",
      "railways",
      "petrol",
      "fuel",
      "makemytrip",
      "goibibo",
      "redbus",
      "parking",
      "toll",
      "indian oil",
      "bharat petroleum",
      "hp",
      "shell",
    ],
    color: "yellow",
    icon: "Car",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Entertainment",
    keywords: [
      "netflix",
      "prime video",
      "hotstar",
      "spotify",
      "youtube",
      "inox",
      "pvr",
      "bookmyshow",
      "disney",
      "jiocinema",
      "sonyliv",
      "zee5",
      "voot",
      "gaana",
      "apple music",
    ],
    color: "indigo",
    icon: "Popcorn",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Utilities",
    keywords: [
      "electricity",
      "gas",
      "bescom",
      "bwssb",
      "piped gas",
      "broadband",
      "internet",
      "jio",
      "airtel",
      "vi",
      "vodafone",
      "bsnl",
      "water bill",
      "indane",
      "bharat gas",
      "hp gas",
    ],
    color: "lime",
    icon: "Lightning",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Personal Transfers",
    keywords: [], // Pattern-based detection (UPI to phone numbers)
    color: "gray",
    icon: "ArrowsLeftRight",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Income",
    keywords: [
      "neft cr",
      "interest",
      "salary",
      "zerodha",
      "dividend",
      "refund",
      "cashback",
      "bonus",
      "credit interest",
    ],
    color: "emerald",
    icon: "TrendUp",
    isCustom: false,
    isActive: true,
  },
  {
    name: "Other",
    keywords: [], // Catch-all category
    color: "slate",
    icon: "Question",
    isCustom: false,
    isActive: true,
  },
];

export const CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  orange: { bg: "bg-orange-100", text: "text-orange-700", border: "border-orange-300" },
  green: { bg: "bg-green-100", text: "text-green-700", border: "border-green-300" },
  blue: { bg: "bg-blue-100", text: "text-blue-700", border: "border-blue-300" },
  red: { bg: "bg-red-100", text: "text-red-700", border: "border-red-300" },
  purple: { bg: "bg-purple-100", text: "text-purple-700", border: "border-purple-300" },
  pink: { bg: "bg-pink-100", text: "text-pink-700", border: "border-pink-300" },
  cyan: { bg: "bg-cyan-100", text: "text-cyan-700", border: "border-cyan-300" },
  yellow: { bg: "bg-yellow-100", text: "text-yellow-700", border: "border-yellow-300" },
  indigo: { bg: "bg-indigo-100", text: "text-indigo-700", border: "border-indigo-300" },
  lime: { bg: "bg-lime-100", text: "text-lime-700", border: "border-lime-300" },
  gray: { bg: "bg-gray-100", text: "text-gray-700", border: "border-gray-300" },
  emerald: { bg: "bg-emerald-100", text: "text-emerald-700", border: "border-emerald-300" },
  slate: { bg: "bg-slate-100", text: "text-slate-700", border: "border-slate-300" },
};
